// <auto-generated />
namespace MVC_DataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tablaEventos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tablaEventos));
        
        string IMigrationMetadata.Id
        {
            get { return "202109090030321_tablaEventos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
